sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dockersagiodemo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockersagiodemo/docker-react npm run test