sudo: required
services:
  - docker

before_install:
  - docker build -t dockersagiodemo/docker-react -f Dockerfile.dev .

script:
  - docker run dockersagiodemo/docker-react npm run test -- --coverage